# Generated by Django 5.2.3 on 2025-07-02 00:08

import uuid
from django.db import migrations, models


def generate_tokens(apps, schema_editor):
    Retrospective = apps.get_model('frita', 'Retrospective')
    for retro in Retrospective.objects.all():
        retro.token = uuid.uuid4()
        retro.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0001_initial'),
    ]

    operations = [
        # 1. Adiciona o campo como NULL temporariamente
        migrations.AddField(
            model_name='retrospective',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # 2. Preenche tokens únicos para todos os registros existentes
        migrations.RunPython(generate_tokens),

        # 3. Torna o campo único e obrigatório
        migrations.AlterField(
            model_name='retrospective',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
