# Generated by Django 5.2.3 on 2025-07-02 00:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0002_retrospective_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrospective',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
