# Generated by Django 5.2.2 on 2025-07-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0003_alter_retrospective_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='retro_type',
            field=models.CharField(choices=[('well/not_so_well/new_ideas', 'Well/Not so Well/New Ideas'), ('easy_as_pie', 'Easy As Pie'), ('open_the_box', 'Open the Box')], default='Well/Not so Well/New Ideas', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
