# Generated by Django 5.2.2 on 2025-07-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0004_retrospective_retro_type_alter_card_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrummaster',
            name='username',
        ),
    ]
