# Generated by Django 5.2.3 on 2025-07-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0005_remove_scrummaster_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='0', max_length=10)),
                ('card_id', models.CharField(max_length=10)),
                ('retro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frita.retrospective')),
            ],
        ),
    ]
