# Generated by Django 5.2.3 on 2025-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0006_cardgrouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='name',
            field=models.CharField(default='Retrospectiva não nomeada', max_length=100),
        ),
    ]
