# Generated by Django 5.2.3 on 2025-07-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0007_retrospective_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='#CECECE', max_length=100),
        ),
    ]
