# Generated by Django 5.2.3 on 2025-07-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frita', '0008_card_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardGrouping',
        ),
    ]
